[build]
command = "pip install -r requirements.txt && python app.py build"
publish = "templates"
functions = "netlify-functions"  # Change to the correct path

[build.environment]
FLASK_ENV = "production"
