[build]
command = "pip install -r requirements.txt && python app.py build"
publish = "templates"  # Assuming templates/ is the directory where your index.html resides
functions = "lambda"  # If you have serverless functions

[build.environment]
FLASK_ENV = "production"
